name: Update deps

# Update dependencies each month at the first day of the month
# See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# for more informations.
on:
  schedule:
    - cron: 0 0 1 * *

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: cargo update
        uses: actions-rs/cargo@v1
        with:
          command: update
          args: --workspace

      - name: Open pull request
        uses: peter-evans/create-pull-request@v4.0.3
        with:
          branch: cargo-update
          title: "cargo update"
          commit-message: "cargo update"
          body: "Update dependencies to latest."
